# Generated by Django 4.1.6 on 2023-02-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
