# Generated by Django 4.1.6 on 2023-02-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_productdetail_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=155)),
                ("slug", models.CharField(default="", max_length=255)),
                ("price", models.FloatField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("image", models.CharField(default="", max_length=255)),
                ("images", models.TextField(default="[]")),
                ("specifications", models.TextField(default="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
