# Generated by Django 4.1.6 on 2023-02-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
