# Generated by Django 4.1.6 on 2023-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_product_discount_remove_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=155),
        ),
    ]
