# Generated by Django 4.1.6 on 2023-02-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_productvariant_name_product_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductDetail",
        ),
    ]
