# Generated by Django 4.1.6 on 2023-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_discount_product_image_product_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(max_length=255, upload_to="uploads/products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(max_length=255, upload_to="uploads/products"),
        ),
    ]
