# Generated by Django 4.1.6 on 2023-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_product_image_alter_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number",
            field=models.IntegerField(default="0"),
        ),
    ]
