# Generated by Django 4.1.6 on 2023-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_product_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.TextField(max_length=1000),
        ),
    ]
