# Generated by Django 4.1.6 on 2023-03-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_product_image_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.TextField(blank=True, default=""),
        ),
    ]
