# Generated by Django 4.1.6 on 2023-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_product_type_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
