# Generated by Django 4.1.6 on 2023-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
