# Generated by Django 4.1.6 on 2023-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="children",
            field=models.JSONField(),
        ),
    ]
