# Generated by Django 4.1.6 on 2023-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_address_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="emailCustomer",
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
