# Generated by Django 4.1.6 on 2023-03-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_rename_files_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
